### PR TITLE
Correct comment

### PR DESCRIPTION
**Pull request by rhys-vdw**
Opening this to test Travis

### CODE REVIEW

**Comment by rhys-vdw** [comment]
@PikachuEXE 
image

**Comment by PikachuEXE** [comment]
I think you can trigger a build manually on Travis
Also you can setup regular job/build even if there is not new commit

**Comment by rhys-vdw** [comment]
Yeah, it wasn't listed in the branches there for some reason. I think maybe it only sees them when they're pushed. Either way it looks like we're in business now.

**Comment by PikachuEXE** [comment]
I have already added a build status badge to readme

**Pull request merged**
