### PR TITLE
Use execFile to spawn the source transformer

### LINKED ISSUE #36: Use `child_process.execFile`
Instead of `child_process.exec`.

> The child_process.execFile() function is similar to child_process.exec() except that it does not spawn a shell. Rather, the specified executable file is spawned directly as a new process making it slightly more efficient than child_process.exec().

https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback

### PR DESCRIPTION
**Pull request by a3ammar**
Hi,
This fixes #36. I hope you find the changes appropriate.

### CODE REVIEW

**Comment by a3ammar** [comment]
Sorry! That was unnecessary complex.

**Comment by rhys-vdw** [comment]
Hey Ammar, sorry I haven't had a chance to test and merge this. It looks
perfect. I'm back at the office next week.

**Comment by rhys-vdw** [comment]
Cool. Finally got a chance to test it out. Seems to be working nicely. 👍

**Comment by rhys-vdw** [comment]
Oh, btw, this PR reversed ad2b4f71142ddd2be55ad0f459a9fd49a0a5d933, so I'm going to change it back.

**Comment by rhys-vdw** [comment]
Downside of not having a test suite.

**Comment by a3ammar** [comment]
My understanding is `execFile` does not spawn a shell so you don't need to escape anything. I could take a crack at implementing the tests but I honestly have no idea how I would start with testing a webpack plugin. Do you have examples of similar project to this one that are fully tested?

**Comment by a3ammar** [comment]
At least it ran while the path contained whitespaces, the reason we escaped it in the first place.

**Comment by rhys-vdw** [comment]
> I honestly have no idea how I would start with testing a webpack plugin. Do you have examples of similar project to this one that are fully tested?

I'm also unsure. It's not super pressing at this stage, but it would be better to have tests I guess. It's simple enough that we can get away with it.

> My understanding is execFile does not spawn a shell so you don't need to escape anything.

Oh cool, I hadn't considered that. I'll do a manual test.

**Comment by rhys-vdw** [comment]
Great. Seems to work fine. My bad! :)

**Comment by rhys-vdw** [comment]
[5.0.2](https://github.com/usabilityhub/rails-erb-loader/tree/5.0.2) released. 👍

**Pull request merged**
